//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class EquipmentVachinMachin
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public int VendingMachinId { get; set; }
    
        [JsonIgnore]
        public virtual Equipment Equipment { get; set; }
        [JsonIgnore]
        public virtual VendingMachin VendingMachin { get; set; }
    }
}
