//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class HistoryWeb
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int UserId { get; set; }
        public string ActionDesxription { get; set; }
    
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
