//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> DateSigning { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int StatusReportId { get; set; }
        public byte[] ReportData { get; set; }
        public int VendingMachinId { get; set; }
        public bool NeedInsurance { get; set; }
    
        [JsonIgnore]
        public virtual Company Company { get; set; }
        [JsonIgnore]
        public virtual StatusReport StatusReport { get; set; }
        [JsonIgnore]
        public virtual VendingMachin VendingMachin { get; set; }
    }
}
