//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public int VendingMachinId { get; set; }
        public int ProductId { get; set; }
        public int CountProduct { get; set; }
        public System.DateTime DateTimeSale { get; set; }
        public int TypePayId { get; set; }
    
        [JsonIgnore]
        public virtual Product Product { get; set; }
        [JsonIgnore]
        public virtual TypePay TypePay { get; set; }
        [JsonIgnore]
        public virtual VendingMachin VendingMachin { get; set; }
    }
}
