//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Id { get; set; }
        public int VendingMachinId { get; set; }
        public System.DateTime DateService { get; set; }
        public string Decription { get; set; }
        public string Problems { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string NameEmployee { get; set; }
    
        [JsonIgnore]
        public virtual User User { get; set; }
        [JsonIgnore]
        public virtual VendingMachin VendingMachin { get; set; }
    }
}
