//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class VendingMachin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendingMachin()
        {
            this.EquipmentVachinMachin = new HashSet<EquipmentVachinMachin>();
            this.Incasation = new HashSet<Incasation>();
            this.MachineProduct = new HashSet<MachineProduct>();
            this.MachineTypePay = new HashSet<MachineTypePay>();
            this.Report = new HashSet<Report>();
            this.Sales = new HashSet<Sales>();
            this.Services = new HashSet<Services>();
            this.VendingMachinTypeConnection = new HashSet<VendingMachinTypeConnection>();
        }
    
        public int Id { get; set; }
        public string Adress { get; set; }
        public string Lacation { get; set; }
        public string Coordination { get; set; }
        public string Name { get; set; }
        public int ManufactureId { get; set; }
        public int ModelId { get; set; }
        public int WorkModeId { get; set; }
        public System.DateTime InitWork { get; set; }
        public int StatusMachinId { get; set; }
        public int TotalIncome { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public bool IsDelete { get; set; }
        public bool HaveModem { get; set; }
        public string Notes { get; set; }
        public int TimeZoneId { get; set; }
        public int ProductMatrixId { get; set; }
        public Nullable<int> ShcemaCritValueId { get; set; }
        public Nullable<int> ShcemaNotificationId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> MenedgerId { get; set; }
        public Nullable<int> IngenerId { get; set; }
        public Nullable<int> TapId { get; set; }
        public string PFIDServiece { get; set; }
        public string RFIDIncasation { get; set; }
        public string RFIDDownload { get; set; }
        public string KitOnline { get; set; }
        public int PriotityServiceId { get; set; }
        public Nullable<int> Number { get; set; }
        public string TimeWork { get; set; }
        public Nullable<int> ConnectionProviderId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int PriceInMounth { get; set; }
        public int PaybackMonth { get; set; }
        public int Money { get; set; }
        public int TotalProduct { get; set; }
        public int TypeMachinId { get; set; }
    
        [JsonIgnore]
        public virtual Company Company { get; set; }
        [JsonIgnore]
        public virtual ConnectionProvider ConnectionProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentVachinMachin> EquipmentVachinMachin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incasation> Incasation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineProduct> MachineProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineTypePay> MachineTypePay { get; set; }
        [JsonIgnore]
        public virtual Manufacture Manufacture { get; set; }
        [JsonIgnore]
        public virtual Model Model { get; set; }
        [JsonIgnore]
        public virtual PriotityService PriotityService { get; set; }
        [JsonIgnore]
        public virtual ProductMatrix ProductMatrix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
        [JsonIgnore]
        public virtual ShcemaCritValue ShcemaCritValue { get; set; }
        [JsonIgnore]
        public virtual ShcemaNotification ShcemaNotification { get; set; }
        [JsonIgnore]
        public virtual StatusMachin StatusMachin { get; set; }
        [JsonIgnore]
        public virtual TimeZone TimeZone { get; set; }
        [JsonIgnore]
        public virtual TypeMachine TypeMachine { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
        [JsonIgnore]
        public virtual User User1 { get; set; }
        [JsonIgnore]
        public virtual User User2 { get; set; }
        [JsonIgnore]
        public virtual User User3 { get; set; }
        [JsonIgnore]
        public virtual WorkMode WorkMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendingMachinTypeConnection> VendingMachinTypeConnection { get; set; }
    }
}
