//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
	 using DesktopVendingMachine.Services;
	using System.Linq;
    
    public partial class MachineProduct
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int VendingMachinId { get; set; }
        public int MinProduct { get; set; }
        public int CountProduct { get; set; }
    
        [JsonIgnore]
    
        public virtual Product Product 
        {
            get
            {
                return DataManager.Products.FirstOrDefault(x=>x.Id == ProductId);
            }
            set
            {
            ProductId= value.Id;
            }
        }
        [JsonIgnore]
    
        public virtual VendingMachin VendingMachin 
        {
            get
            {
                return DataManager.VendingMachins.FirstOrDefault(x=>x.Id == VendingMachinId);
            }
            set
            {
            VendingMachinId= value.Id;
            }
        }
    }
}
