//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopVendingMachine.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
	 using DesktopVendingMachine.Services;
	using System.Linq;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Services = new HashSet<Services>();
            this.VendingMachin = new HashSet<VendingMachin>();
            this.VendingMachin1 = new HashSet<VendingMachin>();
            this.VendingMachin2 = new HashSet<VendingMachin>();
            this.VendingMachin3 = new HashSet<VendingMachin>();
            this.CenterNotification = new HashSet<CenterNotification>();
            this.HistoryWeb = new HashSet<HistoryWeb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronic { get; set; }
        public string Email { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Password { get; set; }
        public int CompanyId { get; set; }
        public string Phone { get; set; }
    
        [JsonIgnore]
    
        public virtual Company Company 
        {
            get
            {
                return DataManager.Companys.FirstOrDefault(x=>x.Id == CompanyId);
            }
            set
            {
            CompanyId= value.Id;
            }
        }
        [JsonIgnore]
    
        public virtual Role Role 
        {
            get
            {
                return DataManager.Roles.FirstOrDefault(x=>x.Id == RoleId);
            }
            set
            {
            RoleId= value.Id;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendingMachin> VendingMachin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendingMachin> VendingMachin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendingMachin> VendingMachin2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendingMachin> VendingMachin3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CenterNotification> CenterNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryWeb> HistoryWeb { get; set; }
    }
}
