//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppVendingMachin.Models
{
    using System;
	using Newtonsoft.Json;
	using WebAppVendingMachin.Services;
    using System.Collections.Generic;
    
    public partial class CenterNotification
    {
        public int Id { get; set; }
        public string Notification { get; set; }
        public System.DateTime DateTime { get; set; }
        public int UserId { get; set; }
    
        [JsonIgnore]
    
        public virtual User User 
        {
            get
            {
                return DataManager.Users.FirstOrDefault(x=>x.Id == UserId);
            }
            set
            {
            UserId= value.Id;
            }
        }
    }
}
