//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppVendingMachin.Models
{
    using System;
	using Newtonsoft.Json;
	using WebAppVendingMachin.Services;
    using System.Collections.Generic;
    
    public partial class MachineTypePay
    {
        public int Id { get; set; }
        public int VendingMachinId { get; set; }
        public int TypePayId { get; set; }
    
        [JsonIgnore]
    
        public virtual TypePay TypePay 
        {
            get
            {
                return DataManager.TypePays.FirstOrDefault(x=>x.Id == TypePayId);
            }
            set
            {
            TypePayId= value.Id;
            }
        }
        [JsonIgnore]
    
        public virtual VendingMachin VendingMachin 
        {
            get
            {
                return DataManager.VendingMachins.FirstOrDefault(x=>x.Id == VendingMachinId);
            }
            set
            {
            VendingMachinId= value.Id;
            }
        }
    }
}
